use vstd::prelude::*;

#[macro_use]
#[path = "spec/mod.rs"]
mod db;
#[path = "impl/implementation.rs"]
mod candidate;

use db::DatabaseState;

verus! {

// This wrapper makes an unconstructible implementation fail verification. The
// returned tracked state is the client's initial abstract-map resource; later
// calls consume it through the atomic contracts generated by impl_db!.
fn checked_new() -> (out: (candidate::VerifiedDb, Tracked<DatabaseState>))
    ensures
        out.1@.linked(out.0.id()),
        out.1@.contents == Map::<Seq<char>, i32>::empty(),
{
    candidate::VerifiedDb::new()
}

}

fn main() {}
